# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FivYZ0gcRMCoEUsqxRl5fPRIINPrMXn7
"""

pip install google-genai

from google import genai
from google.genai import types

from google import genai

# Only run this block for Gemini Developer API
client = genai.Client(api_key='AIzaSyBuAT5WSvkvzbJuC_qd4R1vGHwMQqxUvg0')

response = client.models.generate_content(
    model='gemini-2.5-flash',
    contents= 'Why is the sky blue?')

print(response.text)